openapi: 3.2.0
info:
  title: AeroDataBox API - Aviation and Flight Statistical API
  description: Affordable aviation & flight data API tailored for small and medium businesses, teams and individual developers.
  termsOfService: https://aerodatabox.com/terms/
  contact:
    url: https://aerodatabox.com/contact/
  version: 1.14.0.0
servers:
- url: https://prod.api.market/api/v1/aedbx/aerodatabox
security: {}
tags:
- name: Statistical API
paths:
  /airports/{codeType}/{code}/delays:
    parameters:
    - description: API.market API Key
      in: header
      name: x-api-market-key
      value: Please Login/Signup to get an API Key
      required: true
      schema:
        type: string
    get:
      tags:
      - Statistical API
      summary: AeroDataBox Airport Delays (current or Historical Moment) / TIER 3
      description: '**What is the current or historical average delay in the airport?** or **What is the delay index of the airport right now or at a moment in past?**


        Please read more about airport delays on here: https://aerodatabox.com/api-airport-delays/


        *Returns*: Statistical delay information about delays (median delay, delay index, cancelled flights) of arrivals and departures for the requested airport, represented by:

        * a single `AirportDelayContract` item displaying the delay information based on flight movements within the 2 hours prior to the current moment, if no `dateLocal` is specified;

        * a single `AirportDelayContract` item displaying the delay information based on flight movements within the 2 hours prior to the moment requested in `dateLocal`, if `dateLocal` is specified;'
      operationId: GetAirportDelay_DelaysCurrent
      parameters:
      - name: codeType
        in: path
        description: Type of code to search airport by (`iata` or `icao`)
        schema:
          $ref: '#/components/schemas/AirportCodesByEnum'
      - name: code
        in: path
        description: 'If `codeType` is:

          * `icao`, then this field must be a 4-character ICAO-code of the airport (e.g.: EHAM, KLAX, UUEE, etc.);

          * `iata`, then this field must be a 3-character IATA-code of the airport (e.g.: AMS, SFO, LAX, etc.).


          Full, stripped and any case formats are acceptable.'
        required: true
        schema:
          maxLength: 4
          minLength: 3
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirportDelayContract'
              examples:
                GetAirportDelay_DelaysCurrent200Example:
                  summary: Default GetAirportDelay_DelaysCurrent 200 response
                  x-microcks-default: true
                  value:
                    airportIcao: KLAX
                    from: example_value
                    to: example_value
                    departuresDelayInformation: example_value
                    arrivalsDelayInformation: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/AirportDelayContract'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelay_DelaysCurrent400Example:
                  summary: Default GetAirportDelay_DelaysCurrent 400 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelay_DelaysCurrent401Example:
                  summary: Default GetAirportDelay_DelaysCurrent 401 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '451':
          description: Unavailable For Legal Reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelay_DelaysCurrent451Example:
                  summary: Default GetAirportDelay_DelaysCurrent 451 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelay_DelaysCurrent500Example:
                  summary: Default GetAirportDelay_DelaysCurrent 500 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '503':
          description: Service Unavailable
      x-badges:
      - name: TIER 3
        position: before
        color: '#ffb694'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /airports/{codeType}/{code}/delays/{dateLocal}:
    parameters:
    - description: API.market API Key
      in: header
      name: x-api-market-key
      value: Please Login/Signup to get an API Key
      required: true
      schema:
        type: string
    get:
      tags:
      - Statistical API
      summary: AeroDataBox Airport Delays (current or Historical Moment) / TIER 3
      description: '**What is the current or historical average delay in the airport?** or **What is the delay index of the airport right now or at a moment in past?**


        Please read more about airport delays on here: https://aerodatabox.com/api-airport-delays/


        *Returns*: Statistical delay information about delays (median delay, delay index, cancelled flights) of arrivals and departures for the requested airport, represented by:

        * a single `AirportDelayContract` item displaying the delay information based on flight movements within the 2 hours prior to the current moment, if no `dateLocal` is specified;

        * a single `AirportDelayContract` item displaying the delay information based on flight movements within the 2 hours prior to the moment requested in `dateLocal`, if `dateLocal` is specified;'
      operationId: GetAirportDelay_DelaysHistorical
      parameters:
      - name: codeType
        in: path
        description: Type of code to search airport by (`iata` or `icao`)
        schema:
          $ref: '#/components/schemas/AirportCodesByEnum'
      - name: code
        in: path
        description: 'If `codeType` is:

          * `icao`, then this field must be a 4-character ICAO-code of the airport (e.g.: EHAM, KLAX, UUEE, etc.);

          * `iata`, then this field must be a 3-character IATA-code of the airport (e.g.: AMS, SFO, LAX, etc.).


          Full, stripped and any case formats are acceptable.'
        required: true
        schema:
          maxLength: 4
          minLength: 3
          type: string
      - name: dateLocal
        in: path
        description: "The moment of time for / from which delay data is requested (local time, format: YYYY-MM-DDTHH:mm). \nDefault - current time."
        required: true
        schema:
          pattern: \d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?
          type: string
          format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirportDelayContract'
              examples:
                GetAirportDelay_DelaysHistorical200Example:
                  summary: Default GetAirportDelay_DelaysHistorical 200 response
                  x-microcks-default: true
                  value:
                    airportIcao: KLAX
                    from: example_value
                    to: example_value
                    departuresDelayInformation: example_value
                    arrivalsDelayInformation: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/AirportDelayContract'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelay_DelaysHistorical400Example:
                  summary: Default GetAirportDelay_DelaysHistorical 400 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelay_DelaysHistorical401Example:
                  summary: Default GetAirportDelay_DelaysHistorical 401 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '451':
          description: Unavailable For Legal Reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelay_DelaysHistorical451Example:
                  summary: Default GetAirportDelay_DelaysHistorical 451 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelay_DelaysHistorical500Example:
                  summary: Default GetAirportDelay_DelaysHistorical 500 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '503':
          description: Service Unavailable
      x-badges:
      - name: TIER 3
        position: before
        color: '#ffb694'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /airports/{codeType}/{code}/delays/{dateFromLocal}/{dateToLocal}:
    parameters:
    - description: API.market API Key
      in: header
      name: x-api-market-key
      value: Please Login/Signup to get an API Key
      required: true
      schema:
        type: string
    get:
      tags:
      - Statistical API
      summary: AeroDataBox Airport Delays (historical Period) / TIER 3
      description: '**What were the delays within a specific period of time?** or **How the delays changed within a specific period of time?**


        Please read more about airport delays on here: https://aerodatabox.com/api-airport-delays/


        *Returns*: Statistical delay information about delays (median delay, delay index, cancelled flights) of arrivals and departures for the requested airport, represented by a collection of `AiportDelayContract` items displaying the delay information at multiple moments within the period between `dateLocal` and `dateToLocal`.'
      operationId: GetAirportDelays
      parameters:
      - name: codeType
        in: path
        description: Type of code to search airport by (`iata` or `icao`)
        schema:
          $ref: '#/components/schemas/AirportCodesByEnum'
      - name: code
        in: path
        description: 'If `codeType` is:

          * `icao`, then this field must be a 4-character ICAO-code of the airport (e.g.: EHAM, KLAX, UUEE, etc.);

          * `iata`, then this field must be a 3-character IATA-code of the airport (e.g.: AMS, SFO, LAX, etc.).


          Full, stripped and any case formats are acceptable.'
        required: true
        schema:
          maxLength: 4
          minLength: 3
          type: string
      - name: dateFromLocal
        in: path
        description: 'The beginning of the period of time for which delay data is requested (local time, format: YYYY-MM-DDTHH:mm).'
        required: true
        schema:
          pattern: \d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?
          type: string
          format: date-time
      - name: dateToLocal
        in: path
        description: 'The end of the period of time for which delay data is requested (local time, format: YYYY-MM-DDTHH:mm).'
        required: true
        schema:
          pattern: \d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?
          type: string
          format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AirportDelayContract'
              examples:
                GetAirportDelays200Example:
                  summary: Default GetAirportDelays 200 response
                  x-microcks-default: true
                  value:
                  - example_value
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AirportDelayContract'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelays400Example:
                  summary: Default GetAirportDelays 400 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelays401Example:
                  summary: Default GetAirportDelays 401 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '451':
          description: Unavailable For Legal Reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelays451Example:
                  summary: Default GetAirportDelays 451 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetAirportDelays500Example:
                  summary: Default GetAirportDelays 500 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '503':
          description: Service Unavailable
      x-badges:
      - name: TIER 3
        position: before
        color: '#ffb694'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /airports/{codeType}/{code}/stats/routes/daily:
    parameters:
    - description: API.market API Key
      in: header
      name: x-api-market-key
      value: Please Login/Signup to get an API Key
      required: true
      schema:
        type: string
    get:
      tags:
      - Statistical API
      summary: AeroDataBox Airport Routes and Daily Flight Destinations / TIER 3
      description: '**What are the most popular routes from an airport?** or **Where I can fly from an airport?** or

        **How many daily flights to different destinations from an airport?**


        The data will only be available for airports which have at least schedules information available.

        If the airport is also covered with live or ADS-B coverage, the quality will improve greatly as it will

        be based on real data rather than on static scheduled data. To check if an airport is tracked and on which level,

        use `/health/services/airports/{icao}/feeds` endpoint. You can also use `/health/services/feeds/{service}/airports` to get

        the list of covered airports.


        At the moment airports having both ICAO and IATA code and flight schedules are present available only.


        *Returns:* List of routes and daily flights amount departing from an airport.'
      operationId: GetRouteDailyStatistics_RoutesDailyCurrent
      parameters:
      - name: codeType
        in: path
        description: Type of code to search airport by (`iata` or `icao`)
        schema:
          $ref: '#/components/schemas/AirportCodesByEnum'
      - name: code
        in: path
        description: 'If `codeType` is:

          * `icao`, then this field must be a 4-character ICAO-code of the airport (e.g.: EHAM, KLAX, UUEE, etc.);

          * `iata`, then this field must be a 3-character IATA-code of the airport (e.g.: AMS, SFO, LAX, etc.).


          Full, stripped and any case formats are acceptable.'
        required: true
        schema:
          maxLength: 4
          minLength: 3
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyRouteStatContract'
              examples:
                GetRouteDailyStatistics_RoutesDailyCurrent200Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailyCurrent 200 response
                  x-microcks-default: true
                  value:
                    routes:
                    - example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/DailyRouteStatContract'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetRouteDailyStatistics_RoutesDailyCurrent400Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailyCurrent 400 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetRouteDailyStatistics_RoutesDailyCurrent401Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailyCurrent 401 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '451':
          description: Unavailable For Legal Reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetRouteDailyStatistics_RoutesDailyCurrent451Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailyCurrent 451 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetRouteDailyStatistics_RoutesDailyCurrent500Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailyCurrent 500 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '503':
          description: Service Unavailable
      x-badges:
      - name: TIER 3
        position: before
        color: '#ffb694'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /airports/{codeType}/{code}/stats/routes/daily/{dateLocal}:
    parameters:
    - description: API.market API Key
      in: header
      name: x-api-market-key
      value: Please Login/Signup to get an API Key
      required: true
      schema:
        type: string
    get:
      tags:
      - Statistical API
      summary: AeroDataBox Airport Routes and Daily Flight Destinations / TIER 3
      description: '**What are the most popular routes from an airport?** or **Where I can fly from an airport?** or

        **How many daily flights to different destinations from an airport?**


        The data will only be available for airports which have at least schedules information available.

        If the airport is also covered with live or ADS-B coverage, the quality will improve greatly as it will

        be based on real data rather than on static scheduled data. To check if an airport is tracked and on which level,

        use `/health/services/airports/{icao}/feeds` endpoint. You can also use `/health/services/feeds/{service}/airports` to get

        the list of covered airports.


        At the moment airports having both ICAO and IATA code and flight schedules are present available only.


        *Returns:* List of routes and daily flights amount departing from an airport.'
      operationId: GetRouteDailyStatistics_RoutesDailAtSpecificDate
      parameters:
      - name: codeType
        in: path
        description: Type of code to search airport by (`iata` or `icao`)
        schema:
          $ref: '#/components/schemas/AirportCodesByEnum'
      - name: code
        in: path
        description: 'If `codeType` is:

          * `icao`, then this field must be a 4-character ICAO-code of the airport (e.g.: EHAM, KLAX, UUEE, etc.);

          * `iata`, then this field must be a 3-character IATA-code of the airport (e.g.: AMS, SFO, LAX, etc.).


          Full, stripped and any case formats are acceptable.'
        required: true
        schema:
          maxLength: 4
          minLength: 3
          type: string
      - name: dateLocal
        in: path
        description: 'Local date at the airport (default = null).

          If specified, returns statistics based on 7 days prior to the date specified.

          Otherwise, returns statistics based on 7 days prior to the current local date at the airport.'
        required: true
        schema:
          pattern: \d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?
          type: string
          format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyRouteStatContract'
              examples:
                GetRouteDailyStatistics_RoutesDailAtSpecificDate200Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailAtSpecificDate 200 response
                  x-microcks-default: true
                  value:
                    routes:
                    - example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/DailyRouteStatContract'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetRouteDailyStatistics_RoutesDailAtSpecificDate400Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailAtSpecificDate 400 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetRouteDailyStatistics_RoutesDailAtSpecificDate401Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailAtSpecificDate 401 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '451':
          description: Unavailable For Legal Reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetRouteDailyStatistics_RoutesDailAtSpecificDate451Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailAtSpecificDate 451 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetRouteDailyStatistics_RoutesDailAtSpecificDate500Example:
                  summary: Default GetRouteDailyStatistics_RoutesDailAtSpecificDate 500 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '503':
          description: Service Unavailable
      x-badges:
      - name: TIER 3
        position: before
        color: '#ffb694'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /airports/delays:
    parameters:
    - description: API.market API Key
      in: header
      name: x-api-market-key
      value: Please Login/Signup to get an API Key
      required: true
      schema:
        type: string
    get:
      tags:
      - Statistical API
      summary: AeroDataBox Global Delays (current or Historical Moment) / TIER 3
      description: '**What is the current or historical delay situation in all airports?** or **What is the delay index of all airports globally right now or at a moment in past?**


        Please read more about airport delays on here: https://aerodatabox.com/api-airport-delays/


        *Returns*: Statistical delay information about delays (median delay, delay index, cancelled flights) of arrivals and departures for all known airports, represented by a collection of items sorted by

        the average of arrival and departure index, descending order (from worst to best). Only qualifying and recent enough delay statistics records are returned.'
      operationId: GetGlobalDelays_GlobalDelaysCurent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirportDelayContract'
              examples:
                GetGlobalDelays_GlobalDelaysCurent200Example:
                  summary: Default GetGlobalDelays_GlobalDelaysCurent 200 response
                  x-microcks-default: true
                  value:
                    airportIcao: KLAX
                    from: example_value
                    to: example_value
                    departuresDelayInformation: example_value
                    arrivalsDelayInformation: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/AirportDelayContract'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetGlobalDelays_GlobalDelaysCurent400Example:
                  summary: Default GetGlobalDelays_GlobalDelaysCurent 400 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetGlobalDelays_GlobalDelaysCurent401Example:
                  summary: Default GetGlobalDelays_GlobalDelaysCurent 401 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '451':
          description: Unavailable For Legal Reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetGlobalDelays_GlobalDelaysCurent451Example:
                  summary: Default GetGlobalDelays_GlobalDelaysCurent 451 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetGlobalDelays_GlobalDelaysCurent500Example:
                  summary: Default GetGlobalDelays_GlobalDelaysCurent 500 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '503':
          description: Service Unavailable
      x-badges:
      - name: TIER 3
        position: before
        color: '#ffb694'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /airports/delays/{dateUtc}:
    parameters:
    - description: API.market API Key
      in: header
      name: x-api-market-key
      value: Please Login/Signup to get an API Key
      required: true
      schema:
        type: string
    get:
      tags:
      - Statistical API
      summary: AeroDataBox Global Delays (current or Historical Moment) / TIER 3
      description: '**What is the current or historical delay situation in all airports?** or **What is the delay index of all airports globally right now or at a moment in past?**


        Please read more about airport delays on here: https://aerodatabox.com/api-airport-delays/


        *Returns*: Statistical delay information about delays (median delay, delay index, cancelled flights) of arrivals and departures for all known airports, represented by a collection of items sorted by

        the average of arrival and departure index, descending order (from worst to best). Only qualifying and recent enough delay statistics records are returned.'
      operationId: GetGlobalDelays_GlobalDelaysAtSpecificDate
      parameters:
      - name: dateUtc
        in: path
        description: 'The moment of time for / from which delay data is requested (UTC time, format: YYYY-MM-DDTHH:mm).

          Default - current time.'
        required: true
        schema:
          pattern: \d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?
          type: string
          format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirportDelayContract'
              examples:
                GetGlobalDelays_GlobalDelaysAtSpecificDate200Example:
                  summary: Default GetGlobalDelays_GlobalDelaysAtSpecificDate 200 response
                  x-microcks-default: true
                  value:
                    airportIcao: KLAX
                    from: example_value
                    to: example_value
                    departuresDelayInformation: example_value
                    arrivalsDelayInformation: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/AirportDelayContract'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetGlobalDelays_GlobalDelaysAtSpecificDate400Example:
                  summary: Default GetGlobalDelays_GlobalDelaysAtSpecificDate 400 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetGlobalDelays_GlobalDelaysAtSpecificDate401Example:
                  summary: Default GetGlobalDelays_GlobalDelaysAtSpecificDate 401 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '451':
          description: Unavailable For Legal Reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetGlobalDelays_GlobalDelaysAtSpecificDate451Example:
                  summary: Default GetGlobalDelays_GlobalDelaysAtSpecificDate 451 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetGlobalDelays_GlobalDelaysAtSpecificDate500Example:
                  summary: Default GetGlobalDelays_GlobalDelaysAtSpecificDate 500 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '503':
          description: Service Unavailable
      x-badges:
      - name: TIER 3
        position: before
        color: '#ffb694'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /flights/{number}/delays:
    parameters:
    - description: API.market API Key
      in: header
      name: x-api-market-key
      value: Please Login/Signup to get an API Key
      required: true
      schema:
        type: string
    get:
      tags:
      - Statistical API
      summary: AeroDataBox Flight Delay Statistics by Flight Number / TIER 3
      description: '**By how much the flight is delayed in average?**


        Information is only available for flights which were tracked with live updates at least at origin or at destination within the last 90 days.


        *Returns:* delay statistics for the flight with specified number.'
      operationId: GetFlightDelays
      parameters:
      - name: number
        in: path
        description: Flight number (with or without spaces, IATA or ICAO, any case formats are acceptable, e.g. KL1395, Klm 1395)
        required: true
        schema:
          maxLength: 8
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightLegDelayContract'
              examples:
                GetFlightDelays200Example:
                  summary: Default GetFlightDelays 200 response
                  x-microcks-default: true
                  value:
                    number: example_value
                    origins:
                    - example_value
                    destinations:
                    - example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/FlightLegDelayContract'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetFlightDelays400Example:
                  summary: Default GetFlightDelays 400 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetFlightDelays401Example:
                  summary: Default GetFlightDelays 401 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '451':
          description: Unavailable For Legal Reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetFlightDelays451Example:
                  summary: Default GetFlightDelays 451 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorContract'
              examples:
                GetFlightDelays500Example:
                  summary: Default GetFlightDelays 500 response
                  x-microcks-default: true
                  value:
                    message: example_value
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorContract'
        '503':
          description: Service Unavailable
      x-badges:
      - name: TIER 3
        position: before
        color: '#ffb694'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    DelayBracketContract:
      required:
      - num
      type: object
      properties:
        delayedFrom:
          type:
          - string
          - 'null'
          description: 'The beginning of the delay range (format: [-]hh:mm:ss).

            E.g. in the expresssion "delayed from 30 to 60 minutes" stands for "from 30 minutes".

            Value can be negative (therefore, means early occurence).


            Must be preset if "DelayedTo" is not specified.'
          format: date-span
        delayedTo:
          type:
          - string
          - 'null'
          description: 'The end of the delay range (format: [-]hh:mm:ss).

            E.g. in the expresssion "delayed from 30 to 60 minutes" stands for "to 60 minutes".

            Value can be negative (therefore, means early occurence).


            Must be preset if "DelayedFrom" is not specified.'
          format: date-span
        num:
          type: integer
          description: Count of records subject to a specified delay range
          format: int32
        percentage:
          type:
          - number
          - 'null'
          description: 'Percentage of records subject to a specified delay range.


            Only available when this delay bracket is provided as a part

            of a statistical information of a bigger context and the "total"

            count of records is known.'
          format: float
      additionalProperties: false
      description: Delay bracket contract describing how many records are subject to a specific delay range
    DailyRouteStatRecordContract:
      required:
      - averageDailyFlights
      - destination
      - operators
      type: object
      properties:
        destination:
          $ref: '#/components/schemas/ListingAirportContract'
        averageDailyFlights:
          type: number
          description: Daily average of flights per destination
          format: float
        operators:
          type: array
          items:
            $ref: '#/components/schemas/FlightAirlineContract'
          description: Airlines operating on the route
      additionalProperties: false
      description: Statistical record of route daily statistics
    ListingAirportContract:
      required:
      - name
      type: object
      properties:
        icao:
          type:
          - string
          - 'null'
          description: ICAO code of the airport
        iata:
          type:
          - string
          - 'null'
          description: IATA code of the airport
        localCode:
          type:
          - string
          - 'null'
          description: Code of the airport within the local or national codification system
        name:
          minLength: 1
          type: string
          description: Name of the airport
        shortName:
          type:
          - string
          - 'null'
          description: Shortened name of the airport
        municipalityName:
          type:
          - string
          - 'null'
          description: Name of the municipality this airport belongs to
        location:
          $ref: '#/components/schemas/GeoCoordinatesContract'
        countryCode:
          type:
          - string
          - 'null'
          description: Two-letter country code of the airport
        timeZone:
          type:
          - string
          - 'null'
          description: Time zone of the airport in Olson format (e.g. "Europe/Amsterdam")
      additionalProperties: false
      description: Flight's airport reference contract
    FlightLegDelayContract:
      required:
      - number
      type: object
      properties:
        number:
          minLength: 1
          type: string
          description: Flight number
        origins:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/FlightDelayContract'
          description: Delay statistics of flight on departure at origins
        destinations:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/FlightDelayContract'
          description: Delay statistics of flight on arrival at destinations
      additionalProperties: false
      description: Delay statistics of a flight leg
    DailyRouteStatContract:
      required:
      - routes
      type: object
      properties:
        routes:
          type: array
          items:
            $ref: '#/components/schemas/DailyRouteStatRecordContract'
      additionalProperties: false
      description: Route daily statistics of the airport
    FlightDelayContract:
      required:
      - airportIcao
      - class
      - delayPercentiles
      - fromUtc
      - medianDelay
      - numConsideredFlights
      - numFlightsDelayedBrackets
      - toUtc
      type: object
      properties:
        airportIcao:
          minLength: 1
          type: string
          description: ICAO code of the airport at which statistics is observed
        class:
          $ref: '#/components/schemas/StatisticClass'
        scheduledHourUtc:
          type:
          - integer
          - 'null'
          description: 'Hour on which flight is scheduled (represented in UTC).


            If provided, it separates the statistics for the same flight departing/arriving at different time of day

            on different days within the observed period.'
          format: int32
        medianDelay:
          type: string
          description: 'Median historic delay of the flight (format: [-]hh:mm:ss).

            Value can be negative (therefore, means early occurence).'
          format: date-span
        delayPercentiles:
          type: array
          items:
            $ref: '#/components/schemas/PercentileBracketContract'
          description: "Distribution of historic delays of the flight in percentiles from 5 percentile to 95 percentile in steps of 5 percentile, \nallowing for a more detailed analysis of delay patterns beyond simple averages or medians."
        numConsideredFlights:
          type: integer
          description: 'The number of flight movements taken into account to calculate this

            statistics.'
          format: int32
        numFlightsDelayedBrackets:
          type: array
          items:
            $ref: '#/components/schemas/DelayBracketContract'
          description: 'Brackets containing information more detailed information about

            how many flights were delayed/early per specific delay range brackets

            (e.g. late from 15 to 30 minutes, from 30 to 60, etc.)'
        fromUtc:
          type: string
          description: The beginning of the time range within which flght delay information is calculated (represented in UTC time)
          format: date-time
        toUtc:
          type: string
          description: The end of the time range within which flght delay information is calculated (represented in UTC time)
          format: date-time
      additionalProperties: false
      description: Delay statistics for a flight movement
    ErrorContract:
      required:
      - message
      type: object
      properties:
        message:
          minLength: 1
          type: string
          description: Error message
      additionalProperties: false
      description: Error response
    StatisticClass:
      enum:
      - Flight
      - FlightAndHour
      type: string
      description: '<p>Possible values:</p>

        <ul>

        <li><b>0 - Flight</b></li>

        <li><b>1 - FlightAndHour</b></li>

        </ul>

        '
    FlightAirlineContract:
      required:
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: Airline name
        iata:
          type:
          - string
          - 'null'
          description: IATA code of the airline
        icao:
          type:
          - string
          - 'null'
          description: ICAO code of the airline
      additionalProperties: false
      description: Flight's airline reference conract
    GeoCoordinatesContract:
      required:
      - lat
      - lon
      type: object
      properties:
        lat:
          maximum: 90
          minimum: -90
          type: number
          description: Latitude, in degrees
          format: float
        lon:
          maximum: 180
          minimum: -180
          type: number
          description: Longitude, in degrees
          format: float
      additionalProperties: false
      description: Geographical coordinates data
    FlightBatchDelayContract:
      required:
      - numCancelled
      - numQualifiedTotal
      - numTotal
      type: object
      properties:
        numTotal:
          type: integer
          description: Total number of flights in the the batch (including cancelled)
          format: int32
        numQualifiedTotal:
          type: integer
          description: 'Total number of flights in the batch, which were used to to calculate the

            delay information (including cancelled). Should equal to or less than `NumTotal`.


            The closer the value of this property to the value of `NumTotal`, the higher the

            reliability of delay information'
          format: int32
        numCancelled:
          type: integer
          description: Total amount of flights in the batch
          format: int32
        medianDelay:
          type:
          - string
          - 'null'
          description: 'Median delay of flights in the batch (format: [-]hh:mm:ss).

            Value can be negative (therefore, means early occurence).'
          format: date-span
        delayIndex:
          type:
          - number
          - 'null'
          description: Normalized value on scale from 0.0 to 5.0 which corresponds with current amount of delays and cancellations in a given batch of flights (the less - the better).
          format: float
      additionalProperties: false
      description: Delay information about a batch of flights
    AirportDelayContract:
      required:
      - airportIcao
      - arrivalsDelayInformation
      - departuresDelayInformation
      - from
      - to
      type: object
      properties:
        airportIcao:
          minLength: 1
          type: string
          description: Airport ICAO code
        from:
          $ref: '#/components/schemas/DateTimeContract'
        to:
          $ref: '#/components/schemas/DateTimeContract'
        departuresDelayInformation:
          $ref: '#/components/schemas/FlightBatchDelayContract'
        arrivalsDelayInformation:
          $ref: '#/components/schemas/FlightBatchDelayContract'
      additionalProperties: false
    PercentileBracketContract:
      required:
      - delay
      - percentile
      type: object
      properties:
        percentile:
          maximum: 95
          minimum: 5
          type: integer
          description: Percentile of the distribution
          format: int32
        delay:
          type: string
          description: 'Delay of the flight for the specific percentile (format: [-]hh:mm:ss).'
          format: date-span
      additionalProperties: false
      description: Percentile bracket contract describing the flight delay for a specific percentile of the distribution
    DateTimeContract:
      required:
      - local
      - utc
      type: object
      properties:
        utc:
          type: string
          description: UTC-time
          format: date-time
        local:
          type: string
          description: Local time
          format: date-time
      additionalProperties: false
      description: Descriptor date-time represented in both UTC and local timezones
    AirportCodesByEnum:
      enum:
      - Icao
      - Iata
      type: string
      description: 'Search by airport code type<p>Possible values:</p>

        <ul>

        <li><b>0 - Icao</b>: ICAO-code</li>

        <li><b>1 - Iata</b>: IATA-code</li>

        </ul>

        '
